#!/usr/local/bin/python3

# Below, see a sample of /var/log/messages.
#
# ---------- begin sample log extract ----------
# Jan 20 03:25:08 fakehost logrotate: ALERT exited abnormally with [1]
# Jan 20 03:25:09 fakehost run-parts(/etc/cron.daily)[20447]: finished logrotate
# Jan 20 03:26:21 fakehost anacron[28969]: Job 'cron.daily' terminated
# Jan 20 03:26:22 fakehost anacron[28969]: Normal exit (1 job run)
# Jan 20 03:30:01 fakehost CROND[31462]: (root) CMD (/usr/lib64/sa/sa1 1 1)
# Jan 20 03:30:01 fakehost CROND[31461]: (root) CMD (/var/system/bin/sys-cmd -F > /dev/null 2>&1)
# Jan 20 05:03:03 fakehost ntpd[3705]: synchronized to time.faux.biz, stratum 2
# Jan 20 05:20:01 fakehost rsyslogd: [origin software="rsyslogd" swVersion="5.8.10" x-pid="20438" x-info="http://www.rsyslog.com"] start
# Jan 20 05:22:04 fakehost cs3[31163]:  Q: ".../bin/rsync -LD ": symlink has no referent: "/var/syscmds/fakehost/runit_scripts/etc/runit/service/superImportantService/run"#012Q: ".../bin/rsync -LD ": rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
# Jan 20 05:22:04 fakehost cs3[31163]:  I: Last 2 quoted lines were generated by "/usr/local/bin/rsync -LD --recursive --delete --password-file=/var/syscmds/modules/rsync_password /var/syscmds/fakehost syscmds@fakehost::syscmds_rsync"
# Jan 20 05:22:08 fakehost cs3[31163]:  Q: ".../sbin/sv restart": ok: run: /export/service/cool-service: (pid 32323) 0s
# Jan 20 05:22:08 fakehost cs3[31163]:  I: Last 1 quoted lines were generated by "/sbin/sv restart /export/service/cool-service"
# Jan 20 05:22:09 fakehost cs3[31163]:  R: cs3:  The cool service on fakehost does not appear to be communicating with the cool service leader.  Automating a restart of the cool service in attempt to resolve the communication problem.
# Jan 20 05:22:37 fakehost ACCT_ADD: WARNING: Manifest /var/syscmds/inputs/config-general/doit.txt has been processed already, bailing
# ---------- end sample log extract ----------
#
# Write a script which parses /var/log/messages and generates a CSV that looks like the following
#
# ---------- begin sample output ----------
# minute,total_messages,logrotate,run-parts,anacron,CROND,ntpd,rsyslogd,cs3,ACCT_ADD
# Jan 20 03:25,22,1,2,3,3,2,0,7,4
# Jan 20 03:26,2,0,0,0,0,0,0,0,2
# Jan 20 03:30,20,9,8,3,0,0,0,0,0
# Jan 20 05:03,10,4,6,0,0,0,0,0,0
# ---------- end sample output ------------

# NOTE: that the list of programs is not fixed, but needs to be dynamicly
# generated

# AWB NOTES: Again with bash here. Probably should have used python
# but again, I felt like stopping to google something would have been
# frowned upon

# I accidentally deleted my solution
# but it looked something like this

 # get minute and total_messages
"""
calc_cnt () {
   month=$1
   day=$2
   minute=$3
   pattern=$4

   cnt=$(cat /tmp/log.txt | awk -v month="$month" -v day="$day" -v minute="$minute" -v pattern="$pattern" \
     '$1==month && $2==day && $3~minute && $5~pattern {print $1,$2,$3}' | sort | wc -l )

   echo $cnt
}

 echo  "minute,total_messages,logrotate,run-parts,anacron,CROND,ntpd,rsyslogd,cs3,ACCT_ADD" >> logs.csv
 cat /tmp/log.txt | awk -F[:] '{print $1":"$2}' | sort | uniq -c | while read cnt month day minute
 do
    #logrotate_cnt=$(cat /var/log/messages | awk -v month="$month" -v day="$day" -v minute="$minute" '$1==month && $2==day && $3~minute && $5~/logrotate/ {print $1,$2,$3}' | sort |wc -l)
    #run_parts_cnt=$(cat /var/log/messages | awk -v month="$month" -v day="$day" -v minute="$minute" '$1==month && $2==day && $3~minute && $5~/run-parts/ {print $1,$2,$3}' | sort |wc -l)
    #anacron_cnt=$(cat /var/log/messages | awk -v month="$month" -v day="$day" -v minute="$minute" '$1==month && $2==day && $3~minute && $5~/anacron/ {print $1,$2,$3}' | sort |wc -l)
    #crond_cnt=$(cat /var/log/messages | awk -v month="$month" -v day="$day" -v minute="$minute" '$1==month && $2==day && $3~minute && $5~/CROND/ {print $1,$2,$3}' | sort |wc -l)
    #ntpd_cnt=$(cat /var/log/messages | awk -v month="$month" -v day="$day" -v minute="$minute" '$1==month && $2==day && $3~minute && $5~/ntpd/ {print $1,$2,$3}' | sort |wc -l)
    #rsyslogd_cnt=$(cat /var/log/messages | awk -v month="$month" -v day="$day" -v minute="$minute" '$1==month && $2==day && $3~minute && $5~/rsyslogd/ {print $1,$2,$3}' | sort |wc -l)
    #cs3_cnt=$(cat /var/log/messages | awk -v month="$month" -v day="$day" -v minute="$minute" '$1==month && $2==day && $3~minute && $5~/cs3/ {print $1,$2,$3}' | sort |wc -l)
    #acct_add_cnt=$(cat /var/log/messages | awk -v month="$month" -v day="$day" -v minute="$minute" '$1==month && $2==day && $3~minute && $5~/ACCT_ADD/ {print $1,$2,$3}' | sort |wc -l)
    
   logrotate_cnt=$(calc_cnt $month $day $minute logrotate)
   run_parts_cnt=$(calc_cnt $month $day $minute run-parts)
   anacron_cnt=$(calc_cnt $month $day $minute anacron)
   crond_cnt=$(calc_cnt $month $day $minute CROND)
   ntpd_cnt=$(calc_cnt $month $day $minute ntpd)
   rsyslogd_cnt=$(calc_cnt $month $day $minute rsyslogd)
   cs3_cnt=$(calc_cnt $month $day $minute cs3)
   acct_add_cnt=$(calc_cnt $month $day $minute ACCT_ADD)

    total_cnt=$(expr $logrotate_cnt + $run_parts_cnt + $anacron_cnt + $crond_cnt + $ntpd_cnt + $rsyslogd_cnt + $cs3_cnt + $acct_add_cnt)
    echo  $month" "$day" "$minute","$total_cnt","$logrotate_cnt","$run_parts_cnt","$anacron_cnt","$crond_cnt","$ntpd_cnt","$rsyslogd_cnt","$cs3_cnt","$acct_add_cnt

 done >> logs.csv
"""
# Andy Cai, due to right now seems less people know bash as well as us during interview, so rewrite using python
# Per the interviewer, the results as above sample CSV file, actually the program is dynamically, for example:
# Jan 20 03:25:08 fakehost logrotate: ALERT exited abnormally with [1]
# Jan 20 03:25:09 fakehost run-parts(/etc/cron.daily)[20447]: finished logrotate
# above two lines, need return
# minute,total,logrotate,run-parts
# Jan 20 03:25,2,1,1
#
# and at same second u will get same program like below example: at 05:22:04 below
# Jan 20 05:22:04 fakehost cs3[31163]:  Q: ".../bin/rsync -LD ": symlink has no referent: "/var/syscmds/fakehost/runit_scripts/etc/runit/service/superImportantService/run"#012Q: ".../bin/rsync -LD ": rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
# Jan 20 05:22:04 fakehost cs3[31163]:  I: Last 2 quoted lines were generated by "/usr/local/bin/rsync -LD --recursive --delete --password-file=/var/syscmds/modules/rsync_password /var/syscmds/fakehost syscmds@fakehost::syscmds_rsync"
# Jan 20 05:22:08 fakehost cs3[31163]:  Q: ".../sbin/sv restart": ok: run: /export/service/cool-service: (pid 32323) 0s
# Jan 20 05:22:08 fakehost cs3[31163]:  I: Last 1 quoted lines were generated by "/sbin/sv restart /export/service/cool-service"
# Jan 20 05:22:09 fakehost cs3[31163]:  R: cs3:  The cool service on fakehost does not appear to be communicating with the cool service leader.  Automating a restart of the cool service in attempt to resolve the communication problem.
# Jan 20 05:22:37 fakehost ACCT_ADD: WARNING: Manifest /var/syscmds/inputs/config-general/doit.txt has been processed already, bailing
# above lines, should return
# minute,total,cs3[31163],ACCT_ADD
# Jan 20 05:22,6,5,1


def countLog (logFile):
    f = open(logFile,"r")

    minutes = {}
    program_names = {}
    cnt = 1
    for line in f:
        m = line.split(' ')
        minute = m[0] + " " + m[1] + " " + m[2][0:5]
        program = m[4].replace(":","").strip()
        programs = {}

        # get program names to support print
        program_names[program] = True

        if minute in minutes.keys():
            if program in minutes[minute].keys():
                minutes[minute][program] = minutes[minute][program] + 1
            else:
                minutes[minute][program] = cnt
        else:
                programs[program] = cnt
                minutes[minute] = programs
    f.close()

    return minutes, program_names

def genCSV (csvFile, fileData):
    f = open(csvFile, "a")
    f.write(fileData)
    f.close()

if __name__ == "__main__":
    logFile = "/tmp/log.txt"
    csvFile = "./output.csv"

    # count minute numbers in /var/log/messages
    (minutes, program_names) = countLog(logFile)
    #print(program_names.keys())

    # print title
    title = "minute,total_messages"
    for t in program_names.keys():
        title += "," + t
    #print(title)
    title += "\n"
    genCSV(csvFile,title)
    
    # generate CSV
    for minute in minutes.keys():
         # get total messages for minute
        total = 0
        for cnt in minutes[minute].values():
            total += cnt

        data = minute + "," + str(total)

        for program in program_names.keys():
            if program in minutes[minute].keys():
                program_cnt = "," + str(minutes[minute][program])
            else:
                program_cnt = ",0" 
        #for program in minutes[minute].keys():
         #   program_cnt_str = "," + str(minutes[minute][program])
            data += program_cnt

        data += "\n"
        
        genCSV(csvFile, data)
